services:
  - type: web
    name: learning-tracker-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT_JSON
        sync: false
